{
 "title": "kdb+",
 "description": "Example dashboard for kdb+ instances",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Server",
    "label": "Server",
    "query": "label_values(up{job=\"kdb\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Open Handles",
   "type": "singlestat",
   "description": "Total number of files opened by the user. This does not count files opened by the kdb+ sub system.",
   "gridPos": { "h": 1, "w": 21, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kdb_handles_total{instance=\"$Server\"}",
     "legendFormat": "Opened IPC File Descriptors"
    }
   ]
  },
  {
   "title": "kdb+ Host Memory",
   "type": "graph",
   "description": "Relationship between kdb+ memory usage and memory provided by machine. NOTE: this does not take into account other processes",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "memory_physical_bytes{instance=\"$Server\"}",
     "legendFormat": "Hosts physical memory"
    },
    {
     "expr": "memory_heap_peak_bytes{instance=\"$Server\"}",
     "legendFormat": "kdb+ memory peak"
    },
    {
     "expr": "memory_heap_limit_bytes{instance=\"$Server\"}",
     "legendFormat": "kdb+ enforced memory limit"
    },
    {
     "expr": "memory_heap_bytes{instance=\"$Server\"}",
     "legendFormat": "kdb+ heap memory"
    },
    {
     "expr": "memory_usage_bytes{instance=\"$Server\"}",
     "legendFormat": "kdb+ used memory"
    }
   ]
  },
  {
   "title": "Sync Requests",
   "type": "heatmap",
   "description": "Requests aligned in latency buckets. Brighter blobs mean more requests received, when compared to other timespans within that request type.",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "rate(kdb_sync_histogram_seconds{instance=\"$Server\"}[30s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ASync Requests",
   "type": "heatmap",
   "description": "Requests aligned in latency buckets. Brighter blobs mean more requests received, when compared to other timespans within that request type.",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "rate(kdb_async_histogram_seconds{instance=\"$Server\"}[30s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "kdb+ Internal Memory Usage",
   "type": "graph",
   "description": "Representation of internal kdb+ memory use",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "memory_usage_bytes{instance=\"$Server\"}",
     "legendFormat": "kdb+ used memory"
    },
    {
     "expr": "memory_heap_bytes{instance=\"$Server\"}",
     "legendFormat": "kdb+ heap memory"
    },
    {
     "expr": "memory_mapped_bytes{instance=\"$Server\"}",
     "legendFormat": "kdb+ memory mapped files"
    },
    {
     "expr": "kdb_syms_memory_bytes{instance=\"$Server\"}",
     "legendFormat": "kdb+ symbol memory"
    }
   ]
  },
  {
   "title": "HTTP Get Requests",
   "type": "heatmap",
   "description": "Requests aligned in latency buckets. Brighter blobs mean more requests received, when compared to other timespans within that request type.",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "rate(kdb_http_get_histogram_seconds{instance=\"$Server\"}[30s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Machine Memory Used",
   "type": "bargauge",
   "description": "Percentage of heap used by kdb+ in relation to the physical machine memory",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(memory_heap_bytes{instance=~\"$Server\"} / memory_physical_bytes{instance=\"$Server\"}) * 100"
    }
   ]
  },
  {
   "title": "HTTP Post Requests",
   "type": "heatmap",
   "description": "Requests aligned in latency buckets. Brighter blobs mean more requests received, when compared to other timespans within that request type.",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "rate(kdb_http_post_histogram_seconds{instance=\"$Server\"}[30s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Symbol Count",
   "type": "singlestat",
   "description": "The number of internalised symbols. An extreme amount may indicate bad use of the symbol type.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kdb_syms_total{instance=\"$Server\"}",
     "legendFormat": "Symbol Count"
    }
   ]
  },
  {
   "title": "Opened IPC File Descriptors",
   "type": "singlestat",
   "description": "Total number of files opened by the user. This does not count files opened by the kdb+ sub system.",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kdb_ipc_opened_total{instance=\"$Server\"}",
     "legendFormat": "Opened IPC File Descriptors"
    }
   ]
  },
  {
   "title": "Sync Requests / s",
   "type": "singlestat",
   "description": "Total number of files opened by the user. This does not count files opened by the kdb+ sub system.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kdb_sync_total{instance=\"$Server\"}[1m])",
     "legendFormat": "Opened IPC File Descriptors"
    }
   ]
  },
  {
   "title": "Async Requests / s",
   "type": "singlestat",
   "description": "Total number of files opened by the user. This does not count files opened by the kdb+ sub system.",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kdb_async_total{instance=\"$Server\"}[1m])",
     "legendFormat": "Opened IPC File Descriptors"
    }
   ]
  },
  {
   "title": "Web Socket Connections",
   "type": "heatmap",
   "description": "Requests aligned in latency buckets. Brighter blobs mean more requests received, when compared to other timespans within that request type.",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "rate(kdb_ws_histogram_seconds{instance=\"$Server\"}[30s])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Get Requests / s",
   "type": "singlestat",
   "description": "Total number of files opened by the user. This does not count files opened by the kdb+ sub system.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kdb_http_get_total{instance=\"$Server\"}[1m])",
     "legendFormat": "Opened IPC File Descriptors"
    }
   ]
  },
  {
   "title": "Web Socket Messages / s",
   "type": "singlestat",
   "description": "Total number of files opened by the user. This does not count files opened by the kdb+ sub system.",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kdb_ws_total{instance=\"$Server\"}[1m])",
     "legendFormat": "Opened IPC File Descriptors"
    }
   ]
  },
  {
   "title": "Timer Calls / s",
   "type": "singlestat",
   "description": "Total number of files opened by the user. This does not count files opened by the kdb+ sub system.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kdb_ts_total{instance=\"$Server\"}[1m])",
     "legendFormat": "Opened IPC File Descriptors"
    }
   ]
  },
  {
   "title": "Timers",
   "type": "heatmap",
   "description": "Requests aligned in latency buckets. Brighter blobs mean more requests received, when compared to other timespans within that request type.",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "rate(kdb_ts_histogram_seconds{instance=\"$Server\"}[30s])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}